
package se.ifmo.ru.soap.impl;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import se.ifmo.ru.soap.api.Flat;
import se.ifmo.ru.soap.api.FlatGetResponseDto;
import se.ifmo.ru.soap.api.FlatsGetListRequestDto;
import se.ifmo.ru.soap.api.FlatsGetListResponseDto;
import se.ifmo.ru.soap.api.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FlatsWebService", targetNamespace = "http://api.web.ru.ifmo.se/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FlatsWebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns se.ifmo.ru.web.api.FlatGetResponseDto
     * @throws VerificationException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addFlat", targetNamespace = "http://api.web.ru.ifmo.se/", className = "se.ifmo.ru.web.api.AddFlat")
    @ResponseWrapper(localName = "addFlatResponse", targetNamespace = "http://api.web.ru.ifmo.se/", className = "se.ifmo.ru.web.api.AddFlatResponse")
    public FlatGetResponseDto addFlat(
        @WebParam(name = "arg0", targetNamespace = "")
        Flat arg0)
        throws VerificationException
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns se.ifmo.ru.web.api.FlatsGetListResponseDto
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFlats", targetNamespace = "http://api.web.ru.ifmo.se/", className = "se.ifmo.ru.web.api.GetFlats")
    @ResponseWrapper(localName = "getFlatsResponse", targetNamespace = "http://api.web.ru.ifmo.se/", className = "se.ifmo.ru.web.api.GetFlatsResponse")
    public FlatsGetListResponseDto getFlats(
        @WebParam(name = "arg0", targetNamespace = "")
        FlatsGetListRequestDto arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns long
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "countByNew", targetNamespace = "http://api.web.ru.ifmo.se/", className = "se.ifmo.ru.web.api.CountByNew")
    @ResponseWrapper(localName = "countByNewResponse", targetNamespace = "http://api.web.ru.ifmo.se/", className = "se.ifmo.ru.web.api.CountByNewResponse")
    public long countByNew(
        @WebParam(name = "arg0", targetNamespace = "")
        Boolean arg0);

    /**
     * 
     * @return
     *     returns se.ifmo.ru.web.api.FlatGetResponseDto
     * @throws NotFoundException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getWithMaxId", targetNamespace = "http://api.web.ru.ifmo.se/", className = "se.ifmo.ru.web.api.GetWithMaxId")
    @ResponseWrapper(localName = "getWithMaxIdResponse", targetNamespace = "http://api.web.ru.ifmo.se/", className = "se.ifmo.ru.web.api.GetWithMaxIdResponse")
    public FlatGetResponseDto getWithMaxId()
        throws NotFoundException
    ;

    /**
     * 
     * @return
     *     returns long
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sumHeight", targetNamespace = "http://api.web.ru.ifmo.se/", className = "se.ifmo.ru.web.api.SumHeight")
    @ResponseWrapper(localName = "sumHeightResponse", targetNamespace = "http://api.web.ru.ifmo.se/", className = "se.ifmo.ru.web.api.SumHeightResponse")
    public long sumHeight();

    /**
     * 
     * @param arg0
     * @return
     *     returns se.ifmo.ru.web.api.FlatGetResponseDto
     * @throws NotFoundException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFlat", targetNamespace = "http://api.web.ru.ifmo.se/", className = "se.ifmo.ru.web.api.GetFlat")
    @ResponseWrapper(localName = "getFlatResponse", targetNamespace = "http://api.web.ru.ifmo.se/", className = "se.ifmo.ru.web.api.GetFlatResponse")
    public FlatGetResponseDto getFlat(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0)
        throws NotFoundException
    ;

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Oneway
    @RequestWrapper(localName = "deleteFlat", targetNamespace = "http://api.web.ru.ifmo.se/", className = "se.ifmo.ru.web.api.DeleteFlat")
    public void deleteFlat(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns se.ifmo.ru.web.api.FlatGetResponseDto
     * @throws VerificationException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateFlat", targetNamespace = "http://api.web.ru.ifmo.se/", className = "se.ifmo.ru.web.api.UpdateFlat")
    @ResponseWrapper(localName = "updateFlatResponse", targetNamespace = "http://api.web.ru.ifmo.se/", className = "se.ifmo.ru.web.api.UpdateFlatResponse")
    public FlatGetResponseDto updateFlat(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Flat arg1)
        throws VerificationException
    ;

}
