
package se.ifmo.ru.soap.impl;

import javax.xml.ws.WebFault;
import se.ifmo.ru.soap.api.NotFoundFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "NotFoundFault", targetNamespace = "http://api.web.ru.ifmo.se/")
public class NotFoundException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private NotFoundFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public NotFoundException(String message, NotFoundFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public NotFoundException(String message, NotFoundFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: se.ifmo.ru.web.api.NotFoundFault
     */
    public NotFoundFault getFaultInfo() {
        return faultInfo;
    }

}
